name: Build

on:
  push:
    branches:
      - main
# Defaults for every job and step in this workflow
defaults:
  run:
    shell: bash # Run everything using bash

# Global environment variables
env:
  # Easy way to set the node version
  NODE_VERSION: '16'

# This workflow file contains four jobs, three to build the corresponding
# releases on all three supported platforms, and a last one, which will
# create the release draft.
jobs:
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  #                                                                           #
  #                          PREPARE RELEASE DRAFT                            #
  #                                                                           #
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  # After the three builds, this job downloads all assets, creates and verifies
  # SHA256 checksums, and finally creates a release draft and uploads all
  # assets to it. NOTE: If the workflow detects a nightly is being built, this
  # step rather uploads the binaries to the Zettlr server instead of creating
  # a release draft.
  prepare_release:
    name: Prepare release draft
    runs-on: ubuntu-latest
    steps:
      - name: Clone client repository (main branch)
        uses: actions/checkout@v3
        with:
          ref: 'main'
          path: 'client'
      - name: Clone private desktop repository (main branch)
        uses: actions/checkout@v3
        with:
          ref: 'main'
          repository: azernis/desktop
          token: ${{ secrets.GH_PAT }}
      - name: Setup NodeJS ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Set up build environment
        run: npm install --ci
      - name: Retrieve tag version
        id: ref
        run: |
          pkgver=$(node ./build/scripts/getPkgVersion.js)
          echo ::set-output name=version::$pkgver
      # Create a new release draft
      - name: Create release draft
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Populate the inputs of the release we already know
          tag_name: v${{steps.ref.outputs.version}}
          name: Release v${{steps.ref.outputs.version}}
          body: If you can read this, we have forgotten to fill in the changelog. Sorry!
          draft: true # Always create as draft, so that we can populate the remaining values easily
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  #                                                                           #
  #                              WINDOWS BUILDS                               #
  #                                                                           #
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  build_win:
    name: Windows build
    # Make sure (and wait until) the setup has succeeded
    needs: [prepare_release]
    runs-on: windows-latest
    steps:
      # Check out main from desktop for a regular release
      - name: Clone client repository (main branch)
        uses: actions/checkout@v3
        with:
          ref: 'main'
          path: 'client'
      - name: Clone private desktop repository (main branch)
        uses: actions/checkout@v3
        with:
          ref: 'main'
          repository: azernis/desktop
          token: ${{ secrets.GH_PAT }}
      - name: Setup NodeJS ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Set up build environment
        run: npm install --ci
      # see https://www.zettlr.com/post/continuous-cross-platform-deployment-github-actions
      - name: Retrieve tag version
        id: ref
        run: |
          pkgver=$(node ./build/scripts/getPkgVersion.js)
          echo ::set-output name=version::$pkgver
      # Create the windows binaries.
      - name: Build NSIS installer (x64)
        run: npm run dist-win-x64
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_LINK: ${{ secrets.WIN_CERT }}
          CSC_KEY_PASSWORD: ${{ secrets.WIN_CERT_PASS }}
      # Now we need to cache all artifacts. We create one artifact per build
      # step. It should be noted that "artifacts" are more like file shares.
      # Thus they can contain multiple files.

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  #                                                                           #
  #                               MACOS BUILDS                                #
  #                                                                           #
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  build_macos:
    name: macOS build
    # Make sure (and wait until) the setup has succeeded
    needs: [prepare_release]
    runs-on: macos-latest
    steps:
      # Check out main from desktop for a regular release
      - name: Clone client repository (main branch)
        uses: actions/checkout@v3
        with:
          ref: 'main'
          path: 'client'
      - name: Clone private desktop repository (main branch)
        uses: actions/checkout@v3
        with:
          ref: 'main'
          repository: azernis/desktop
          token: ${{ secrets.GH_PAT }}
      - name: Setup NodeJS ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Set up build environment
        run: npm install --ci
      - name: Retrieve tag version
        id: ref
        run: |
          pkgver=$(node ./build/scripts/getPkgVersion.js)
          echo ::set-output name=version::$pkgver
      # Now, finally build the app itself. 
      - name: Build macOS image file
        run: npm run dist-mac
        env:
          CSC_LINK: ${{ secrets.MACOS_CERT }}
          CSC_KEY_PASSWORD: ${{ secrets.MACOS_CERT_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}